todo/urls.py
from django.contrib import admin
from django.urls import path,include
from todo1 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo1.urls')),
]

todo1/urls.py
from django.urls import path
from . import views

app_name = 'todo1'

urlpatterns = [
    path('home/', views.home, name='主页'),
    path('edit/', views.edit, name='编辑'),
    path('about/', views.about, name='关于'),
]

todo1/models.py
from django.db import models

# Create your models here.

todo1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'todo1/home.html')

def edit(request):
    return render(request, 'todo1/edit.html')

def about(request):
    return render(request, 'todo1/about.html')

todo1/templates/todo1/about.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>关于本站</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        #topnav{
            font-size: 1.35em;
            padding-left: 5em;
            padding-right: 5em;
            height: 2.5em;
        }
        nav input{
          width: 39%!important;
        }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'todo1:主页' %}">待办清单</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end">
          <input class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <br>
      <h4>一款小巧、简洁的待办清单工具，帮你规划日常事务。</h4>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

todo1/templates/todo1/edit.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>编辑待办事项</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        #topnav{
            font-size: 1.35em;
            padding-left: 5em;
            padding-right: 5em;
            height: 2.5em;
        }
        nav input{
          width: 39%!important;
        }
        #form-edit{
           margin-left:8em;
           margin-right:8em;
        }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'todo1:主页' %}">待办清单</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'todo1:关于' %}">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end">
          <input class="form-control mr-sm-2 " type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0 " type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <br>
      <form id="form-edit">
        <div class="form-group">
          <label for="editTodo"></label>
          <input class="form-control form-control-lg" id="editTodo" type="text" value="遛狗">
          <small id="help" class="form-text text-muted">在这里编辑待办事项</small>
        </div>
        <button type="button" class="btn btn-primary btn-lg btn-block">提交</button>
      </form>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

todo1/templates/todo1/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>你的个人待办清单</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        #topnav{
            font-size: 1.35em;
            padding-left: 5em;
            padding-right: 5em;
            height: 2.5em;
        }
        nav input{
          width: 39%!important;
        }
        .no-underline>tr>td>a:hover{
          text-decoration: none;
        }
        #line-through{
          text-decoration: line-through;
        }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="topnav">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo1:主页' %}">待办清单</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'todo1:关于' %}">关于本站</a>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0 col-7 justify-content-end">
          <input class="form-control mr-sm-2" type="text" placeholder="待办事项" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">添加</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
      <br>
      <div class="table-responsive">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th>序号</th>
              <th>待办事项</th>
              <th>编辑</th>
              <th>划掉</th>
              <th>删除</th>
            </tr>
          </thead>
          <tbody class="no-underline">
            <tr>
              <th scope="row">1</th>
              <td>小睡一下</td>
              <td><a class="text-success" href="{% url 'todo1:编辑' %}">编辑</a></td>
              <td><a href="#">划掉</a></td>
              <td><a class="text-info" href="#">删除</a></td>
            </tr>
            <tr>
              <th scope="row">2</th>
              <td>看一会小说</td>
              <td><a class="text-success" href="{% url 'todo1:编辑' %}">编辑</a></td>
              <td><a href="#">划掉</a></td>
              <td><a class="text-info" href="#">删除</a></td>
            </tr>
            <tr>
              <th scope="row">3</th>
              <td>散散步</td>
              <td><a class="text-success" href="#">编辑</a></td>
              <td><a href="#">划掉</a></td>
              <td><a class="text-info" href="#">删除</a></td>
            </tr>
            <tr class="table-dark">
              <th class="text-dark" scope="row">4</th>
              <td class="text-dark" id="line-through">去超市</td>
              <td class="text-secondary">不可编辑</td>
              <td><a class="text-info" href="#">撤销</a></td>
              <td><a class="text-danger" href="#">删除</a></td>
            </tr>
          </tbody>
        </table>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://cdn.bootcss.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>